
class BluetoothUuids {
  static const Map<String, String> _uuidMap = {
      "1800": "Generic Access",
      "1801": "Generic Attribute",
      "1802": "Immediate Alert",
      "1803": "Link Loss",
      "1804": "Tx Power",
      "1805": "Current Time Service",
      "1806": "Reference Time Update",
      "1807": "Next DST Change",
      "1808": "Glucose",
      "1809": "Health Thermometer",
      "180a": "Device Information",
      "180d": "Heart Rate",
      "180f": "Battery Service",
      "1812": "Human Interface Device",
      "2a00": "Device Name",
      "2a01": "Appearance",
      "2a02": "Peripheral Privacy Flag",
      "2a03": "Reconnection Address",
      "2a04": "Peripheral Preferred Connection Parameters",
      "2a05": "Service Changed",
      "2a06": "Alert Level",
      "2a07": "Tx Power Level",
      "2a08": "Date Time",
      "2a09": "Day of Week",
      "2a0a": "Day Date Time",
      "2a0c": "Exact Time 256",
      "2a0d": "DST Offset",
      "2a0e": "Time Zone",
      "2a0f": "Local Time Information",
      "2a11": "Time with DST",
      "2a12": "Time Accuracy",
      "2a13": "Time Source",
      "2a14": "Reference Time Information",
      "2a16": "Time Update Control Point",
      "2a17": "Time Update State",
      "2a18": "Glucose Measurement",
      "2a19": "Battery Level",
      "2a1c": "Temperature Measurement",
      "2a1d": "Temperature Type",
      "2a1e": "Intermediate Temperature",
      "2a21": "Measurement Interval",
      "2a22": "Boot Keyboard Input Report",
      "2a23": "System ID",
      "2a24": "Model Number String",
      "2a25": "Serial Number String",
      "2a26": "Firmware Revision String",
      "2a27": "Hardware Revision String",
      "2a28": "Software Revision String",
      "2a29": "Manufacturer Name String",
      "2a2a": "IEEE 11073-20601 Regulatory Certification Data List",
      "2a2b": "Current Time",
      "2a2c": "Magnetic Declination",
      "2a31": "Scan Refresh",
      "2a32": "Boot Keyboard Output Report",
      "2a33": "Boot Mouse Input Report",
      "2a34": "Glucose Measurement Context",
      "2a35": "Blood Pressure Measurement",
      "2a36": "Intermediate Cuff Pressure",
      "2a37": "Heart Rate Measurement",
      "2a38": "Body Sensor Location",
      "2a39": "Heart Rate Control Point",
      "2a3f": "Alert Status",
      "2a40": "Ringer Control Point",
      "2a41": "Ringer Setting",
      "2a42": "Alert Category ID Bit Mask",
      "2a43": "Alert Category ID",
      "2a44": "Alert Notification Control Point",
      "2a45": "Unread Alert Status",
      "2a46": "New Alert",
      "2a47": "Supported New Alert Category",
      "2a48": "Supported Unread Alert Category",
      "2a49": "Blood Pressure Feature",
      "2a4a": "HID Information",
      "2a4b": "Report Map",
      "2a4c": "HID Control Point",
      "2a4d": "Report",
      "2a4e": "Protocol Mode",
      "2a4f": "Scan Interval Window",
      "2a50": "PnP ID",
      "2a51": "Glucose Feature",
      "2a52": "Record Access Control Point",
      "2a53": "RSC Measurement",
      "2a54": "RSC Feature",
      "2a55": "SC Control Point",
      "2a5a": "Aggregate",
      "2a5b": "CSC Measurement",
      "2a5c": "CSC Feature",
      "2a5d": "Sensor Location",
      "2a5e": "PLX Spot-Check Measurement",
      "2a5f": "PLX Continuous Measurement",
      "2a60": "PLX Features",
      "2a63": "Cycling Power Measurement",
      "2a64": "Cycling Power Vector",
      "2a65": "Cycling Power Feature",
      "2a66": "Cycling Power Control Point",
      "2a67": "Location and Speed",
      "2a68": "Navigation",
      "2a69": "Position Quality",
      "2a6a": "LN Feature",
      "2a6b": "LN Control Point",
      "2a6c": "Elevation",
      "2a6d": "Pressure",
      "2a6e": "Temperature",
      "2a6f": "Humidity",
      "2a70": "True Wind Speed",
      "2a71": "True Wind Direction",
      "2a72": "Apparent Wind Speed",
      "2a73": "Apparent Wind Direction",
      "2a74": "Gust Factor",
      "2a75": "Pollen Concentration",
      "2a76": "UV Index",
      "2a77": "Irradiance",
      "2a78": "Rainfall",
      "2a79": "Wind Chill",
      "2a7a": "Heat Index",
      "2a7b": "Dew Point",
      "2a7d": "Descriptor Value Changed",
      "2a7e": "Aerobic Heart Rate Lower Limit",
      "2a7f": "Aerobic Threshold",
      "2a80": "Age",
      "2a81": "Anaerobic Heart Rate Lower Limit",
      "2a82": "Anaerobic Heart Rate Upper Limit",
      "2a83": "Anaerobic Threshold",
      "2a84": "Aerobic Heart Rate Upper Limit",
      "2a85": "Date of Birth",
      "2a86": "Date of Threshold Assessment",
      "2a87": "Email Address",
      "2a88": "Fat Burn Heart Rate Lower Limit",
      "2a89": "Fat Burn Heart Rate Upper Limit",
      "2a8a": "First Name",
      "2a8b": "Five Zone Heart Rate Limits",
      "2a8c": "Gender",
      "2a8d": "Heart Rate Max",
      "2a8e": "Height",
      "2a8f": "Hip Circumference",
      "2a90": "Last Name",
      "2a91": "Maximum Recommended Heart Rate",
      "2a92": "Resting Heart Rate",
      "2a93": "Sport Type for Aerobic and Anaerobic Thresholds",
      "2a94": "Three Zone Heart Rate Limits",
      "2a95": "Two Zone Heart Rate Limits",
      "2a96": "VO2 Max",
      "2a97": "Waist Circumference",
      "2a98": "Weight",
      "2a99": "Database Change Increment",
      "2a9a": "User Index",
      "2a9b": "Body Composition Feature",
      "2a9c": "Body Composition Measurement",
      "2a9d": "Weight Measurement",
      "2a9e": "Weight Scale Feature",
      "2a9f": "User Control Point",
      "2aa0": "Magnetic Flux Density - 2D",
      "2aa1": "Magnetic Flux Density - 3D",
      "2aa2": "Language",
      "2aa3": "Barometric Pressure Trend",
      "2aa4": "Bond Management Control Point",
      "2aa5": "Bond Management Feature",
      "2aa6": "Central Address Resolution",
      "2aa7": "CGM Measurement",
      "2aa8": "CGM Feature",
      "2aa9": "CGM Status",
      "2aaa": "CGM Session Start Time",
      "2aab": "CGM Session Run Time",
      "2aac": "CGM Specific Ops Control Point",
      "2aad": "Indoor Positioning Configuration",
      "2aae": "Latitude",
      "2aaf": "Longitude",
      "2ab0": "Local North Coordinate",
      "2ab1": "Local East Coordinate",
      "2ab2": "Floor Number",
      "2ab3": "Altitude",
      "2ab4": "Uncertainty",
      "2ab5": "Location Name",
      "2ab6": "URI",
      "2ab7": "HTTP Headers",
      "2ab8": "HTTP Status Code",
      "2ab9": "HTTP Entity Body",
      "2aba": "HTTP Control Point",
      "2abb": "HTTPS Security",
      "2abc": "TDS Control Point",
      "2abd": "OTS Feature",
      "2abe": "Object Name",
      "2abf": "Object Type",
      "2ac0": "Object Size",
      "2ac1": "Object First-Created",
      "2ac2": "Object Last-Modified",
      "2ac3": "Object ID",
      "2ac4": "Object Properties",
      "2ac5": "Object Action Control Point",
      "2ac6": "Object List Control Point",
      "2ac7": "Object List Filter",
      "2ac8": "Object Changed",
      "2ac9": "Resolvable Private Address Only",
      "2acc": "Fitness Machine Feature",
      "2acd": "Treadmill Data",
      "2ace": "Cross Trainer Data",
      "2acf": "Step Climber Data",
      "2ad0": "Stair Climber Data",
      "2ad1": "Rower Data",
      "2ad2": "Indoor Bike Data",
      "2ad3": "Training Status",
      "2ad4": "Supported Speed Range",
      "2ad5": "Supported Inclination Range",
      "2ad6": "Supported Resistance Level Range",
      "2ad7": "Supported Heart Rate Range",
      "2ad8": "Supported Power Range",
      "2ad9": "Fitness Machine Control Point",
      "2ada": "Fitness Machine Status",
      "2adb": "Mesh Provisioning Data In",
      "2adc": "Mesh Provisioning Data Out",
      "2add": "Mesh Proxy Data In",
      "2ade": "Mesh Proxy Data Out",
      "2ae0": "Average Current",
      "2ae1": "Average Voltage",
      "2ae2": "Boolean",
      "2ae3": "Chromatic Distance from Planckian",
      "2ae4": "Chromaticity Coordinates",
      "2ae5": "Chromaticity in CCT and Duv Values",
      "2ae6": "Chromaticity Tolerance",
      "2ae7": "CIE 13.3-1995 Color Rendering Index",
      "2ae8": "Coefficient",
      "2ae9": "Correlated Color Temperature",
      "2aea": "Count 16",
      "2aeb": "Count 24",
      "2aec": "Country Code",
      "2aed": "Date UTC",
      "2aee": "Electric Current",
      "2aef": "Electric Current Range",
      "2af0": "Electric Current Specification",
      "2af1": "Electric Current Statistics",
      "2af2": "Energy",
      "2af3": "Energy in a Period of Day",
      "2af4": "Event Statistics",
      "2af5": "Fixed String 16",
      "2af6": "Fixed String 24",
      "2af7": "Fixed String 36",
      "2af8": "Fixed String 8",
      "2af9": "Generic Level",
      "2afa": "Global Trade Item Number",
      "2afb": "Illuminance",
      "2afc": "Luminous Efficacy",
      "2afd": "Luminous Energy",
      "2afe": "Luminous Exposure",
      "2aff": "Luminous Flux",
      "2b00": "Luminous Flux Range",
      "2b01": "Luminous Intensity",
      "2b02": "Mass Flow",
      "2b03": "Perceived Lightness",
      "2b04": "Percentage 8",
      "2b05": "Power",
      "2b06": "Power Specification",
      "2b07": "Relative Runtime in a Current Range",
      "2b08": "Relative Runtime in a Generic Level Range",
      "2b09": "Relative Value in a Voltage Range",
      "2b0a": "Relative Value in an Illuminance Range",
      "2b0b": "Relative Value in a Period of Day",
      "2b0c": "Relative Value in a Temperature Range",
      "2b0d": "Temperature 8",
      "2b0e": "Temperature 8 in a Period of Day",
      "2b0f": "Temperature 8 Statistics",
      "2b10": "Temperature Range",
      "2b11": "Temperature Statistics",
      "2b12": "Time Decihour 8",
      "2b13": "Time Exponential 8",
      "2b14": "Time Hour 24",
      "2b15": "Time Millisecond 24",
      "2b16": "Time Second 16",
      "2b17": "Time Second 8",
      "2b18": "Voltage",
      "2b19": "Voltage Specification",
      "2b1a": "Voltage Statistics",
      "2b1b": "Volume Flow",
      "2b1c": "Chromaticity Coordinate",
      "2b1d": "RC Feature",
      "2b1e": "RC Settings",
      "2b1f": "Reconnection Configuration Control Point",
      "2b20": "IDD Status Changed",
      "2b21": "IDD Status",
      "2b22": "IDD Annunciation Status",
      "2b23": "IDD Features",
      "2b24": "IDD Status Reader Control Point",
      "2b25": "IDD Command Control Point",
      "2b26": "IDD Command Data",
      "2b27": "IDD Record Access Control Point",
      "2b28": "IDD History Data",
      "2b29": "Client Supported Features",
      "2b2a": "Database Hash",
      "2b2b": "BSS Control Point",
      "2b2c": "BSS Response",
      "2b2d": "Emergency ID",
      "2b2e": "Emergency Text",
      "2b2f": "ACS Status",
      "2b30": "ACS Data In",
      "2b31": "ACS Data Out Notify",
      "2b32": "ACS Data Out Indicate",
      "2b33": "ACS Control Point",
      "2b34": "Enhanced Blood Pressure Measurement",
      "2b35": "Enhanced Intermediate Cuff Pressure",
      "2b36": "Blood Pressure Record",
      "2b37": "Registered User",
      "2b38": "BR-EDR Handover Data",
      "2b39": "Bluetooth SIG Data",
      "2b3a": "Server Supported Features",
      "2b3b": "Physical Activity Monitor Features",
      "2b3c": "General Activity Instantaneous Data",
      "2b3d": "General Activity Summary Data",
      "2b3e": "CardioRespiratory Activity Instantaneous Data",
      "2b3f": "CardioRespiratory Activity Summary Data",
      "2b40": "Step Counter Activity Summary Data",
      "2b41": "Sleep Activity Instantaneous Data",
      "2b42": "Sleep Activity Summary Data",
      "2b43": "Physical Activity Monitor Control Point",
      "2b44": "Physical Activity Current Session",
      "2b45": "Physical Activity Session Descriptor",
      "2b46": "Preferred Units",
      "2b47": "High Resolution Height",
      "2b48": "Middle Name",
      "2b49": "Stride Length",
      "2b4a": "Handedness",
      "2b4b": "Device Wearing Position",
      "2b4c": "Four Zone Heart Rate Limits",
      "2b4d": "High Intensity Exercise Threshold",
      "2b4e": "Activity Goal",
      "2b4f": "Sedentary Interval Notification",
      "2b50": "Caloric Intake",
      "2b51": "TMAP Role",
      "2b77": "Audio Input State",
      "2b78": "Gain Settings Attribute",
      "2b79": "Audio Input Type",
      "2b7a": "Audio Input Status",
      "2b7b": "Audio Input Control Point",
      "2b7c": "Audio Input Description",
      "2b7d": "Volume State",
      "2b7e": "Volume Control Point",
      "2b7f": "Volume Flags",
      "2b80": "Volume Offset State",
      "2b81": "Audio Location",
      "2b82": "Volume Offset Control Point",
      "2b83": "Audio Output Description",
      "2b84": "Set Identity Resolving Key",
      "2b85": "Coordinated Set Size",
      "2b86": "Set Member Lock",
      "2b87": "Set Member Rank",
      "2b88": "Encrypted Data Key Material",
      "2b89": "Apparent Energy 32",
      "2b8a": "Apparent Power",
      "2b8b": "Live Health Observations",
      "2b8d": "Cosine of the Angle",
      "2b8e": "Device Time Feature",
      "2b8f": "Device Time Parameters",
      "2b90": "Device Time",
      "2b91": "Device Time Control Point",
      "2b92": "Time Change Log Data",
      "2b93": "Media Player Name",
      "2b94": "Media Player Icon Object ID",
      "2b95": "Media Player Icon URL",
      "2b96": "Track Changed",
      "2b97": "Track Title",
      "2b98": "Track Duration",
      "2b99": "Track Position",
      "2b9a": "Playback Speed",
      "2b9b": "Seeking Speed",
      "2b9c": "Current Track Segments Object ID",
      "2b9d": "Current Track Object ID",
      "2b9e": "Next Track Object ID",
      "2b9f": "Parent Group Object ID",
      "2ba0": "Current Group Object ID",
      "2ba1": "Playing Order",
      "2ba2": "Playing Orders Supported",
      "2ba3": "Media State",
      "2ba4": "Media Control Point",
      "2ba5": "Media Control Point Opcodes Supported",
      "2ba6": "Search Results Object ID",
      "2ba7": "Search Control Point",
      "2ba8": "Energy 32",
      "2bad": "Constant Tone Extension Enable",
      "2bae": "Advertising Constant Tone Extension Minimum Length",
      "2baf": "Advertising Constant Tone Extension Minimum Transmit Count",
      "2bb0": "Advertising Constant Tone Extension Transmit Duration",
      "2bb1": "Advertising Constant Tone Extension Interval",
      "2bb2": "Advertising Constant Tone Extension PHY",
      "2bb3": "Bearer Provider Name",
      "2bb4": "Bearer UCI",
      "2bb5": "Bearer Technology",
      "2bb6": "Bearer URI Schemes Supported List",
      "2bb7": "Bearer Signal Strength",
      "2bb8": "Bearer Signal Strength Reporting Interval",
      "2bb9": "Bearer List Current Calls",
      "2bba": "Content Control ID",
      "2bbb": "Status Flags",
      "2bbc": "Incoming Call Target Bearer URI",
      "2bbd": "Call State",
      "2bbe": "Call Control Point",
      "2bbf": "Call Control Point Optional Opcodes",
      "2bc0": "Termination Reason",
      "2bc1": "Incoming Call",
      "2bc2": "Call Friendly Name",
      "2bc3": "Mute",
      "2bc4": "Sink ASE",
      "2bc5": "Source ASE",
      "2bc6": "ASE Control Point",
      "2bc7": "Broadcast Audio Scan Control Point",
      "2bc8": "Broadcast Receive State",
      "2bc9": "Sink PAC",
      "2bca": "Sink Audio Locations",
      "2bcb": "Source PAC",
      "2bcc": "Source Audio Locations",
      "2bcd": "Available Audio Contexts",
      "2bce": "Supported Audio Contexts",
      "2bcf": "Ammonia Concentration",
      "2bd0": "Carbon Monoxide Concentration",
      "2bd1": "Methane Concentration",
      "2bd2": "Nitrogen Dioxide Concentration",
      "2bd3": "Non-Methane Volatile Organic Compounds Concentration",
      "2bd4": "Ozone Concentration",
      "2bd5": "Particulate Matter - PM1 Concentration",
      "2bd6": "Particulate Matter - PM2.5 Concentration",
      "2bd7": "Particulate Matter - PM10 Concentration",
      "2bd8": "Sulfur Dioxide Concentration",
      "2bd9": "Sulfur Hexafluoride Concentration",
      "2bda": "Hearing Aid Features",
      "2bdb": "Hearing Aid Preset Control Point",
      "2bdc": "Active Preset Index",
      "2bdd": "Stored Health Observations",
      "2bde": "Fixed String 64",
      "2bdf": "High Temperature",
      "2be0": "High Voltage",
      "2be1": "Light Distribution",
      "2be2": "Light Output",
      "2be3": "Light Source Type",
      "2be4": "Noise",
      "2be5": "Relative Runtime in a Correlated Color Temperature Range",
      "2be6": "Time Second 32",
      "2be7": "VOC Concentration",
      "2be8": "Voltage Frequency",
      "2be9": "Battery Critical Status",
      "2bea": "Battery Health Status",
      "2beb": "Battery Health Information",
      "2bec": "Battery Information",
      "2bed": "Battery Level Status",
      "2bee": "Battery Time Status",
      "2bef": "Estimated Service Date",
      "2bf0": "Battery Energy Status",
      "2bf1": "Observation Schedule Changed",
      "2bf2": "Current Elapsed Time",
      "2bf3": "Health Sensor Features",
    }; 

  /// Maps a BLE UUID short code to its human-readable name.
  /// Falls back to the raw [uuid] string if not found.
  static String mapUuids(String uuid) {
    print("Decoding Uuid: ${uuid}, ${_uuidMap[uuid]}");
    return _uuidMap[uuid] ?? uuid;
  }
}